package cm4108.appointment;

import java.util.Date;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

import cm4108.Config;

@DynamoDBTable(tableName=Config.DYNAMODB_TABLE_NAME)
public class Appointment{
	private String id;
	
	private String appUser;
	
	private long appDateTime;
	
	private String duration;
	
	
	private String description;
	
	// default constructor
	public Appointment() {}
	
	public Appointment(long date, String duration, String appUser, String desc) {
		this.setDateTime(date);
		this.setDuration(duration);
		this.setAppUser(appUser);
		this.setDescription(desc);
	}

	@DynamoDBHashKey(attributeName="id")
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@DynamoDBAttribute(attributeName="appDateTime")
	public long getDateTime() {
		return appDateTime;
	}
	@DynamoDBAttribute(attributeName="appUser")
	public String getAppUser() {
		return appUser;
	}

	public void setAppUser(String user) {
		this.appUser = user;
	}

	public void setDateTime(long dateTime) {
		this.appDateTime = dateTime;
	}

	@DynamoDBAttribute(attributeName="duration")
	public String getDuration() {
		return duration;
	}

	public void setDuration(String duration) {
		this.duration = duration;
	}

	@DynamoDBAttribute(attributeName="description")
	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}
	
}
