package cm4108.appointment;

import java.util.Date;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

import cm4108.Config;

@DynamoDBTable(tableName=Config.DYNAMODB_TABLE_NAME)
public class Appointment{
	public String id;
	
	public String dateTime;
	
	public String duration;
	
	public String owner;
	
	public String description;
	
	// default constructor
	public Appointment() {}
	
	public Appointment(String date, String duration, String owner, String desc) {
		this.setDateTime(date);
		this.setDuration(duration);
		this.setOwner(owner);
		this.setDescription(desc);
	}

	@DynamoDBHashKey(attributeName="id")
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@DynamoDBAttribute(attributeName="dateTime")
	public String getDateTime() {
		return dateTime;
	}

	public void setDateTime(String dateTime) {
		this.dateTime = dateTime;
	}

	@DynamoDBAttribute(attributeName="duration")
	public String getDuration() {
		return duration;
	}

	public void setDuration(String duration) {
		this.duration = duration;
	}

	@DynamoDBAttribute(attributeName="owner")
	public String getOwner() {
		return owner;
	}

	public void setOwner(String owner) {
		this.owner = owner;
	}

	@DynamoDBAttribute(attributeName="description")
	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}
	
}
